// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUN30fiKJoAyyK79QC60i8evrR8mSOQxc',
    appId: '1:210325059796:web:c7adc6ec2cc65da5dc2341',
    messagingSenderId: '210325059796',
    projectId: 'hydro-guard-pro',
    authDomain: 'hydro-guard-pro.firebaseapp.com',
    storageBucket: 'hydro-guard-pro.firebasestorage.app',
    measurementId: 'G-L6QY962YLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2zXNc77Uz4rleX09YRHykiU2RTwsHU38',
    appId: '1:210325059796:android:1c59ddf11896965edc2341',
    messagingSenderId: '210325059796',
    projectId: 'hydro-guard-pro',
    storageBucket: 'hydro-guard-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7tx4YKNhD_nupDD4rxSEY1M30ZO8dZvQ',
    appId: '1:210325059796:ios:4117cb21dcadda45dc2341',
    messagingSenderId: '210325059796',
    projectId: 'hydro-guard-pro',
    storageBucket: 'hydro-guard-pro.firebasestorage.app',
    iosBundleId: 'com.example.hydroGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7tx4YKNhD_nupDD4rxSEY1M30ZO8dZvQ',
    appId: '1:210325059796:ios:4117cb21dcadda45dc2341',
    messagingSenderId: '210325059796',
    projectId: 'hydro-guard-pro',
    storageBucket: 'hydro-guard-pro.firebasestorage.app',
    iosBundleId: 'com.example.hydroGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUN30fiKJoAyyK79QC60i8evrR8mSOQxc',
    appId: '1:210325059796:web:d03308e87264bc8cdc2341',
    messagingSenderId: '210325059796',
    projectId: 'hydro-guard-pro',
    authDomain: 'hydro-guard-pro.firebaseapp.com',
    storageBucket: 'hydro-guard-pro.firebasestorage.app',
    measurementId: 'G-3Z3DLZY689',
  );

}